services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    environment:
      - POSTGRES_USER=igortcruz
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=food
    ports:
      - "5432:5432"
    volumes:
      - food_pg_data:/postgres:16

volumes:
  food_pg_data:
